[package]
name = "extobadges"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
select = "0.6.0"
badges = "0.3.2"
toml = "0.7.2"
pico-args = "0.5.0"
anyhow = "1.0.69"
ureq = "2.6.2"
serde = "1.0.152"
